---
- name: Check if Ansible is installed
  command: ansible --version
  register: ansible_check
  changed_when: false
  failed_when: false

- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
  when: "'ansible' in install_packages and ansible_check.rc != 0"

- name: Install Ansible (latest)
  apt:
    name: ansible
    state: present
  when: "'ansible' in install_packages and ansible_check.rc != 0"

- name: Verify Ansible version
  command: ansible --version
  register: ansible_version
  when: "'ansible' in install_packages"

- name: Show Ansible version
  debug:
    msg: |
      Ansible Installation Report:
      {{ ansible_version.stdout | default('Version check failed') }}
      
      Raw output:
      {{ ansible_version }}
  when: "'ansible' in install_packages"


#pass test