- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker
  notify: Restart Docker  # ← Triggers handler at end of playbook

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
  notify: 
    - Restart Docker
    - Update environment  # ← Can notify multiple handlers