---
- name: Check if Terraform is already installed
  ansible.builtin.command: which terraform
  register: terraform_check
  ignore_errors: yes
  changed_when: false
  when: "'terraform' in install_packages"

- name: Ensure HashiCorp directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  when: 
    - "'terraform' in install_packages"
    - terraform_check.rc != 0

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
  when:
    - "'terraform' in install_packages"
    - terraform_check.rc != 0

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
    update_cache: yes
  register: hashicorp_repo_result
  ignore_errors: yes
  when:
    - "'terraform' in install_packages"
    - terraform_check.rc != 0

- name: Install Terraform
  ansible.builtin.apt:
    name: "terraform{% if package_versions.terraform %}={{ package_versions.terraform }}{% endif %}"
    state: present
  register: terraform_install_result
  ignore_errors: yes
  when:
    - "'terraform' in install_packages"
    - terraform_check.rc != 0

- name: Recover from potential HashiCorp repository issues
  block:
    - name: Remove the corrupted file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/hashicorp.list
        state: absent

    - name: Clean up any partial configuration
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes

    - name: Refresh package lists
      ansible.builtin.apt:
        update_cache: yes
  when:
    - "'terraform' in install_packages"
    - terraform_check.rc != 0
    - hashicorp_repo_result.failed or terraform_install_result.failed

- name: Verify Terraform version
  ansible.builtin.command: terraform -version
  register: terraform_version
  changed_when: false
  when: "'terraform' in install_packages"

- name: Show Terraform version
  ansible.builtin.debug:
    msg: "{{ (terraform_version.stdout_lines | default(['Terraform version not available']))[0] }}"
  when: "'terraform' in install_packages"


#pass test